name: video_calling_app
description: A new video calling mobile application using Flutter, Agora SDK and GetX state management.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  agora_rtc_engine: ^5.1.1
  wakelock: ^0.6.1+2
  get_time_ago: ^1.1.4

  device_info_plus: ^3.2.3

  image_picker: ^0.8.5+3
  image_cropper: ^2.0.2
  cached_network_image: ^3.2.0

  connectivity: ^3.0.6
  http: ^0.13.4

  flutter_screenutil: ^5.5.2
  permission_handler: ^9.2.0
  country_code_picker: ^2.0.2

  get: ^4.6.3
  get_storage: ^2.0.3
  built_value: ^8.3.0
  json_annotation: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.1.6

  build_runner: ^2.1.10
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/
